language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: rDIHYqOviAeQ47/6ZOdd01SvQJiY+Iq2VzzSleyq6ZcQx+9Uat+T0i7NCAaiGlZsxIYesNqmusNtM46bQlNNjei838M5hHgu6EA7PsvDzf/V8GmOcaPh2L+NQruJkSDqfKEmO5rrRbSnS+MU8yktak4pRnqH3RHyON044GgXk4qQUHmrT1MsVOZVIywBgqA/GXfH3EDgOxtH4hpfFN8McQUPyl2CLNvFp6HHLiZduWL5nHsHibb92G+G+pVbWFxcJG9GL5AFZoeNuV4GHgHWslVoSvpAWmg06YxqDTjOPn87nnABwL28Sf04Y/gLaAIDoLLuyEaTU8pi9cs9mpgmCdRabIGJU5NU0LZDsY7MV/DoifF5LaeMtFmnvEixtfaUEu92/uMEeDSqdfruW7CzZAMuF4zvCSuY/6ogEGGupC1j0tO5MUQPiKsjZxjs7uRPwIUpq3gxX7+tggrV3luobouBQU9iz8ajgbaB59gM1AcwQV8Uq7gZbYl4v3A77UHOsn712r7eVLDhTWMFTcMKmEAykqytO36AB84nKz2oDjxs3bynAvGlurb7Ke2IkRSUW/Cr3LNJahFxR8n0sUgtoPXpIoMXUVqk+0F5koH8E8yzzqxCvSSrRvvTPMZhXy7veR1KPreoiPte1NeLeOxabmb3BTnBTtXG0yhuLfGCFS4=
  - secure: z/TfOSJP1KuVklCwiJJhBfraRDwZ8z9a1OjZnNCCKF/kO++FYuiczDUJPrAPkM34OL9Mzo1hcw1boLpJMLioyfAhIRPIfcqNPUkeS/9zHjiPwuMqucoWp2gZEx50RnAsfb8cXPRmhU25Xui8vRIPEs02Zsf1CSw1KXow1iscfIfZ7VQzIHWEDUkCuJyA7xTD9MJ+NlpUf1kc+Xg+MgE+/OEwwnsigeSWW3u9WUccl032FXDy6YOOqSA3XVkoU2guSp8ow16xsCw6dad6jkj2Mi/ksxl8nvv3GghudobDx3EgXMoxKFuYAASnnLzhziYDbL+9WMDQG8lhVIyaZW0/xLOJY2mw98ZcTV2F7ZpLQUZtZKlCsJHpJW+gHq+P0Ro3HPyyz72IM9GxqvYk+v3BwMr9H6y7SpsnbWKb/iEYdP/F3yhRr4R4uaP7uudv6yTYB0GnnfY9mzqPmrcpnTjUjBvhA14ESUQ0rDf6YRXeIoL2e35sO3BG3qPbzwpTRac3oNsiZonr0YVx/Bg+U34SkWUhei3PKdATlfRQP1cnCDba23rNTFeCm1auy9svVEZGHN5tFza42Uo19de/ZYXba5ucHrfKAGYne5zkQ2s2gKfOX0hwo7mGvT5K7XAAOInZObcqtHaCjPgRyI01hOOYhK84CLSNN07IpWpdSAxqcvw=
