title = "930 Andalusia Coral Gables 33134"
baseURL = "https://www.featuredlisting.forsale"
tags = ["Coral Gables", "Modernist","Real Estate","Luxury living"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = ""
    author = "futuresarcade"
    description = "captivating oak filled home, walking distance to downtown Coral Gables, Salvador Park and Tennis Courts, Venetian Pool, open kitchen feeds into large family room w/high wood beams, elegant formal dining room overlooks pool, remodeled bathrooms, wood burning fireplace and crown molding throughout, impact resistant windows and accordion shutters"
    logoBig = ""
    logoSmall = ""
    favicon = "favicon.ico"
    opengraphImage = ""
    twitter = ""
    linkedin = ""
    github = ""
    facebook = ""
    email = "o"
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

# [[menu.main]]
#    name = "About"
#    url  = "/#about"
#    weight = 1
# [[menu.main]]
  #  name = "Work"
  #  url  = "/#work"
  #  weight = 2
# [[menu.main]]
#  name = "Blog"
#    url  = "/#blog"
#    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
